/* Generated By:JJTree: Do not edit this line. ASTFunctionExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionExpr extends SimpleNode {
  public ASTFunctionExpr(int id) {
    super(id);
  }

  public ASTFunctionExpr(LispParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LispParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6b4f63e35faa3adda0a1b52471a51b81 (do not edit this line) */
