/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifier extends SimpleNode {
  private String identifier;

  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(LispParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LispParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  
  public void setIdentifier(String identifier_) {
    this.identifier = identifier_;
  
  }

  public String getIdentifier() {
    return this.identifier;
  
  }  
  
}
/* JavaCC - OriginalChecksum=3a8cbce39ab155b7b29673b8a54e32a4 (do not edit this line) */
