/* Generated By:JJTree: Do not edit this line. ASTLambdaExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLambdaExpr extends SimpleNode {
  public ASTLambdaExpr(int id) {
    super(id);
  }

  public ASTLambdaExpr(LispParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LispParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fd6f55eba98d61ab72fba9459729a29b (do not edit this line) */
