/* Generated By:JavaCC: Do not edit this line. LispParserVisitor.java Version 5.0 */
public interface LispParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTFunctionExpr node, Object data);
  public Object visit(ASTNamedFunctionApp node, Object data);
  public Object visit(ASTLambdaExpr node, Object data);
  public Object visit(ASTArithExpr node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=3fbfce31b5bf1dcd4ed8ae2da24656e1 (do not edit this line) */
