/* Generated By:JavaCC: Do not edit this line. LispParserTreeConstants.java Version 5.0 */
public interface LispParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTFUNCTIONEXPR = 1;
  public int JJTNAMEDFUNCTIONAPP = 2;
  public int JJTLAMBDAEXPR = 3;
  public int JJTARITHEXPR = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTNUM = 6;
  public int JJTVOID = 7;


  public String[] jjtNodeName = {
    "Program",
    "FunctionExpr",
    "NamedFunctionApp",
    "LambdaExpr",
    "ArithExpr",
    "Identifier",
    "Num",
    "void",
  };
}
/* JavaCC - OriginalChecksum=fdaa025809cbc8c86f6f7ce102d295f8 (do not edit this line) */
